name = "vuevi"
main = "worker.js"  # entry point for your Worker code
compatibility_date = "2026-02-04"

# Assets directory for your built Vue app
[site]
bucket = "./dist"
entry-point = "workers-site"
